name: build all

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7'

      - name: prepare
        run: |
          make toolchain/install

      - name: build
        run: |
          make V=sc package/compile
          make V=sc package/index

      - name: Upload Built to action
        uses: actions/upload-artifact@v3
        with:
          name: entware-bin
          path: bin
