name: build transmission

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7'

      - name: build
        run: |
          make V=sc toolchain/install
          make V=sc package/transmission/compile
          make V=sc package/index

      - name: push
        run: |
          git add -f bin/targets/armv7-3.2/generic-glibc/packages/*
          git commit -m "tr: update"
          git push
