name: build transmission

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          sudo apt install python2.7
          make package/symlinks
          make toolchain/install

      - name: build
        run: |
          make V=sc package/transmission/compile
          make package/index

      - name: Upload Built to action
        uses: actions/upload-artifact@v3
        with:
          name: entware-bin
          path: bin
